config/routes.rb
Rails.application.routes.draw do
  root 'places#index'
  resources :categories
  resources :places do
    resources :reviews
    resources :galleries
  end
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Place
    can :read, Category
    can :read, Review
    can :read, Gallery

    if user.present?
      can :create, Place
      can :manage, Place, user_id: user.id
      can :create, Review
      can :create, Gallery
      if user.is_admin?
        can :manage, :all
      end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :places
	validates :title, presence: true, 
			  length: { maximum: 30 }
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :place
  belongs_to :user
  has_one_attached :image

  validate :image_type

	private

	def image_type
		if image.attached? == false
			errors.add(:image, "is missing")
		elsif !image.content_type.in?(%("image/jpeg image/png"))
				errors.add(:image, "needs to be JPEG or PNG or JPG")
		end
	end
end

app/models/place.rb
class Place < ApplicationRecord
	paginates_per 20
  belongs_to :user
  belongs_to :category
  has_many :reviews, :dependent => :destroy
  has_many :galleries, :dependent => :destroy
  has_one_attached :image
  validates :title, presence: true, 
			  length: { maximum: 30 }
	validates :desc, presence: true, 
			  length: { maximum: 300 }
	validates :agreement, inclusion: { in: [true] }
	validate :image_type

	def self.search_by(search_term)
		where("LOWER(title) LIKE :search_term",
		search_term: "%#{search_term.downcase}%")
	end

	private

	def image_type
		if image.attached? == false
			errors.add(:image, "is missing")
		elsif !image.content_type.in?(%("image/jpeg image/png"))
				errors.add(:image, "needs to be JPEG or PNG or JPG")
		end
	end
end

app/models/review.rb
class Review < ApplicationRecord
	paginates_per 5
  belongs_to :user
  belongs_to :place

  validates :body, length: { maximum: 300 }
  validates :quality, presence: true, 
			  numericality: { only_integer: true, 
			  				  greater_than_or_equal_to: 1, 
			  				  less_than_or_equal_to: 5 }
	validates :service, presence: true, 
			  numericality: { only_integer: true, 
			  				  greater_than_or_equal_to: 1, 
			  				  less_than_or_equal_to: 5 }
	validates :interior, presence: true, 
			  numericality: { only_integer: true, 
			  				  greater_than_or_equal_to: 1, 
			  				  less_than_or_equal_to: 5 }

	def average_raitings 
		average_raitings =	(Review.average(:quality) + Review.average(:service) + Review.average(:interior))/3
		sprintf("%.2f", average_raitings) 
	end

	def average_quality
		quality = Review.average(:quality)
		sprintf("%.2f", quality) 
	end

	def average_service 
		service= Review.average(:service)
		sprintf("%.2f", service) 
	end

	def average_interior 
		interior = Review.average(:interior)
		sprintf("%.2f", interior)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :places
  has_many :reviews
  has_many :galleries
  validates :name, presence: true, 
			  length: { maximum: 30 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show]
  def index
  	@categories = Category.all
  end

  def show
    @categories = Category.all
  end

  private

  def set_category
  	@category = Category.find(params[:id])
  end

  def genre_params
  	params.require(:category).permit(:title)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @gallery = current_user.galleries.build(gallery_params)
		@gallery.place = @place
		if @gallery.save
      flash[:success] = "Review is successfully added!"
    else
      flash[:warning] = "Incorrect!"
    end
    redirect_to @place
  end

 

  private

 

  def gallery_params

    params.require(:gallery).permit(:image)

  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  load_and_authorize_resource

  before_action :set_place, only: [:edit, :update, :destroy]

  def index
    @places = Place.order(:title).page params[:page]
    @categories = Category.all
  if params[:search]
    @search_term = params[:search]
    @places = @places.search_by(@search_term)
  end
  end

  def new
    @place = Place.new
  end

  def show
    @place = Place.find(params[:id])
    @review = Review.new
    @gallery = Gallery.new
    @reviews = @place.reviews.order(:created_at).page params[:page]
  end

  def create
    @place = current_user.places.build(place_params)
    if @place.save
      flash[:success] = "Place is successfully added!"
      redirect_to @place
    else
      flash[:warning] = "Incorrect!"
      render 'edit'
    end
  end

  def edit
  end

  def update
    @place.update(place_params)
    if @place.save
      flash[:success] = "Place is successfully updated!"
      redirect_to @place
    else
      flash[:warning] = "Incorrect!"
      render 'edit'
    end
  end

  def destroy
    @place.destroy
    flash[:success] = "Place is successfully deleted"
    redirect_to root_path
  end
  

  private
  def place_params
    params.require(:place).permit(:title, :desc, :agreement, :category_id, :user_id, :image)
  end

  def set_place
    @place = current_user.places.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.order(:created_at).page params[:page]
  end


  def create
    @place = Place.find(params[:place_id])
    @review = current_user.reviews.build(review_params)
		@review.place = @place
		if @review.save
      flash[:success] = "Review is successfully added!"
    else
      flash[:warning] = "Incorrect!"
    end
    redirect_to @place
  end

  private

  def review_params
    params.require(:review).permit(:body, :quality, :service, :interior)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/index.html.erb
<table class="table table-striped">
    <tr>
    	<th>Title</th>
    </tr>
    <% @categories.each do |category| %>
    <tr>
    	<td><%= link_to category.title, category_path(category) %></td>
     </tr>
    <% end %> 
  </table>

app/views/categories/show.html.erb
<p><%= @category.title %></p>

<div class="mb-3">
    <%= link_to 'All', root_path %>
    <% @categories.each do |category| %>
      <div class="d-inline-block m-2"><%= link_to category.title, category_path(category) %></div> 
    <% end %>
  </div>

<div class="row">
  <% @category.places.each do |place| %>
  <div class="col-sm-3 mb-2">
    <div class="card">
      <div class="card-body">
        <div><%= image_tag place.image.variant(resize: "200x150!") %></div>
        <h5 class="card-title"><%= link_to place.title, place %></h5>
        <p>By: <%= place.user.name %></p>
      </div>
    </div>
  </div>
  
  <% end %>
</div>

app/views/galleries/_form.html.erb
<div>
<%= simple_form_for([@place, @gallery]) do |f| %>
		<%= f.input :image, label: 'Upload new photo:', error: 'Cannot be blank, please add main photo' %>

		<div>
			<%= f.button :submit %>
		</div>
	<% end %>
</div>

app/views/galleries/_gallery.html.erb
<div class="d-inline-block mr-2"><%= image_tag gallery.image.variant(resize: "100x100!") %></div>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
    <head>
      <title>FinalAijan</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="container">
      <div class="mb-2">
        <nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
          <div class="container">
            <%= link_to 'Reviewer', root_path, class: 'navbar-brand' %>
            <div class="w-50 nav-item ml-auto">
              <%= form_for "", url: places_path, role: "search", method: :get do%>
                <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
              <% end %>
            </div>
            <div class="navbar-nav ml-auto">           
              <% if user_signed_in? %>
                <div class="nav-item">
                  <span class="navbar-text">
                    Hello, <%= current_user.name %>
                  <span>
                </div>
                <div class="nav-item">
                  <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'nav-link' %>
                </div>
                <div class="nav-item">    
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </div>
                <div>
              <% else %>
                <div class="nav-item">
                  <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                </div>
                <div class="nav-item">
                  <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                </div>
              <% end %>
            </div>
          </div>
        </nav>
      </div>
      <div class="pt-3">
        <%= yield %>
      </div>
    </body>
  </html>

app/views/places/_form.html.erb
<div class="container">
	<%= simple_form_for @place do |f| %>
		<%= f.input :title, label: 'Title', error: 'Cannot be blank, please add title' %>
		<%= f.association :category %>
		<%= f.input :desc, label: 'Description', error: 'Cannot be blank, please add description' %>
		<%= f.input :agreement, label: 'By submiting this form, you agree that following information will be submitted to the public domain, and administrators of this site will have full control over the said information.', error: 'Cannot be blank, please check the box' %>
		<%= f.input :image, label: 'Main photo', error: 'Cannot be blank, please add main photo' %>

		<%= f.button :submit %>
	<% end %>
</div>

app/views/places/edit.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div class="mt-5">

  <div>
    <%= link_to 'All', root_path %>
    <% @categories.each do |category| %>
      <div class="d-inline-block"><%= link_to category.title, category_path(category) %></div> 
    <% end %>
  </div>

<br>

  <div class="mb-5">
    <h4 class="d-inline mr-3 ml-3">All places</h4> 
    <% if can? :create, Place%> 
      <div> <%= link_to 'Add new place', new_place_path, class: 'btn btn-light border' %>
      </div>
    <% end %>
  </div>
  
  <div class="row">
    <% @places.each do |place| %>
      <div class="col-sm-3 mb-2">
        <div class="card">
          <div class="card-body">
            <div><%= link_to image_tag(place.image.variant(resize: "200x150!")), place %></div>
            <h5 class="card-title"><%= link_to place.title, place %></h5>
            <p>By: <%= place.user.name %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div> <%= paginate @places%> </div>
</div>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<div class="mt-5 pt-5">
  <p id="notice"><%= notice %></p>

  <h3>
    <strong>Title:</strong>
    <%= @place.title %>
  </h3>
  <div class="d-inline-block w-50">
   Description: <%= @place.desc %>
  </div>
  <div class="d-inline-block ml-5">
  <%= image_tag @place.image.variant(resize: "300x200!") %>
  </div>
  <div>
    <% if @place.user == current_user %> 
    	<div class="mt-2 d-inline-block"><%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-secondary' %></div>
    	<div class="mt-2 d-inline-block"><%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Do you want to delete this place?'}, class: 'btn btn-secondary' %></div>
    <% end %>

  	<div class="mt-2 d-inline-block"><%= link_to 'Back', places_path, class: 'btn btn-secondary' %></div> 
  </div>
  <hr>
  <div class="mt-2 mb-4">
    <h4>Gallery</h4>
      <%= render @place.galleries %>
  </div>
  <hr>
  <div>
    <h4>Raitings</h4>
    <p><b>Overall: </b><%= @review.average_raitings %></p>
    <p>Quality of food: <%= @review.average_quality %></p>
    <p>Service quality: <%= @review.average_service %></p>
    <p>Interior: <%= @review.average_interior %></p>
  </div>
  <hr>
  <h4>Reviews</h4>

    <div>
      <%= render @place.reviews %>
    </div>

  <h4>Add review:</h4>
    <%= render 'reviews/form' %>
  <hr>
  <h4>Add review:</h4>
  <%= render 'galleries/form' %>

</div>

app/views/reviews/_form.html.erb
<div>
<%= simple_form_for([@place, @review]) do |f| %>
		<div>
			<%= f.input :body, label: 'Add review', error: 'This review is too long' %>
		</div>
		<div class="d-inline-block mr-2">
			<%= f.input :quality, collection: 1..5, label: 'Quality of food', error: 'Cannot be blank' %>
		</div>
		<div class="d-inline-block mr-2">
			<%= f.input :service, collection: 1..5, label: 'Service quality', error: 'Cannot be blank' %>
		</div>
		<div class="d-inline-block">
			<%= f.input :interior, collection: 1..5, label: 'Interior', error: 'Cannot be blank' %>
		</div>
		<div>
			<%= f.button :submit %>
		</div>
	<% end %>
</div>

app/views/reviews/_review.html.erb
<div>
  <p>By: <%= review.user.name %></p>
  <p>
    <%= review.body %>
  </p>
  <p>
    <%= review.quality %>
  </p>
  <p>
    <%= review.service %>
  </p>
  <p>
    <%= review.interior %>
  </p>
<div>